config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'about' => 'pages#about'

  resources :players, only: [:index, :show]
  resources :game_stats, only: [:index, :show]
  resources :champions, only: [:index, :show]

end

app/models/champion.rb
class Champion < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/models/game_stat.rb
class GameStat < ActiveRecord::Base
	belongs_to :player
end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :game_stats

	def update
		UpdateJob.perform_later(self)
	end

	def get_stats
		champs_played = $champion_map.select do |id, name|
			self.game_stats.exists?(champion: id)
		end

		champ_stats = champs_played.map do |id, name|
			get_champ_stats(id, name)
		end
		champ_stats.sort_by{ |champ| champ["wins"] }.sort_by{ |champ| champ["games"] }.reverse
	end

	def get_champ_stats(id, name)
		games = self.game_stats.where("champion = ?", id).count
		{"champion" => name,
		 "games" => games,
		 "wins" => self.game_stats.where("champion = ? AND win = ?", id, true).count,
		 "losses" => self.game_stats.where("champion = ? AND win = ?", id, false).count,
		 "kills" => self.game_stats.where("champion = ?", id).average("kills").round(1),
		 "deaths" => self.game_stats.where("champion = ?", id).average("deaths").round(1),
		 "assists" => self.game_stats.where("champion = ?", id).average("assists").round(1),
		 "cs" => self.game_stats.where("champion = ?", id).average("cs").round(1),
		 "gold" => self.game_stats.where("champion = ?", id).average("gold").round(1),
		 "wards_placed" => self.game_stats.where("champion = ?", id).average("wards_placed").round(1),
		 "greens" => self.game_stats.where("champion = ?", id).average("greens").round(1),
		 "pinks" => self.game_stats.where("champion = ?", id).average("pinks").round(1)}
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController

	def index
		@champs_contested = $champion_map.select do |id, name|
			GameStat.exists?(champion: id)
		end
		@sorted_champ_stats = get_all_champ_stats(@champs_contested)
	end

	def show
		@champion = Champion.find(params[:id])
		@sorted_player_stats = get_player_stats(@champion)
	end

	def get_all_champ_stats(champs)
		champ_stats = champs.map do |id, name|
			times_banned = Game.where("blue_1 = ? OR
									   blue_2 = ? OR
									   blue_3 = ? OR
									   purple_1 = ? OR
									   purple_2 = ? OR
									   purple_3 = ?", id, id, id, id, id, id).count
			times_picked = GameStat.where("champion = ?", id).count
			wins = GameStat.where("champion = ? AND win = ?", id, true).count
			{"champion" => name,
			 "contests" => times_banned + times_picked,
			 "contest_rate" => ( (times_banned + times_picked).to_f / Game.count * 100).round(1),
			 "picks" => times_picked,
			 "bans" => times_banned,
			 "winrate" => (wins.to_f / times_picked * 100).round(1),
			 "wins" => wins,
			 "losses" => GameStat.where("champion = ? AND win = ?", id, false).count}
		end
		champ_stats.sort_by{ |champ| champ["contests"] }.reverse
	end

	def get_player_stats(champ)
		ids = GameStat.where("champion = ?", champ.champ_id).select(:player_id).group(:player_id).to_a
		player_stats = ids.map do |id|
			player = Player.find(id.player_id)
			{"object" => player,
			 "stats" => player.get_champ_stats(champ.champ_id, champ.name)}
		end
		player_stats.sort_by{ |player| player["stats"]["wins"] }.
					 sort_by{ |player| player["stats"]["games"] }.reverse
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	def index
		@players = Player.all
		@min = params[:minimum].nil? ? 5 : params[:minimum].to_i
		@sorted_winrates = get_winrates(@players, @min)
	end

	def show
		@player = Player.find(params[:id])
		@sorted_stats = @player.get_stats
	end

	def get_winrates(players, min)
		winrates = players.select{ |player| player.game_stats.count >= min }.map do |player|
			{"object" => player,
			 "wins" => player.game_stats.where("win = ?", true).count,
			 "losses" => player.game_stats.where("win = ?", false).count,
			 "winrate" => (player.game_stats.where("win = ?", true).count.to_f /
						  player.game_stats.count * 100).round(1)}
		end
		winrates.sort_by{ |player| player["wins"] }.sort_by{ |player| player["winrate"] }.reverse
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/champions/index.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Champion</th>
					<th>Contests</th>
					<th>Contest Rate</th>
					<th>Picks</th>
					<th>Bans</th>
					<th>Winrate</th>
					<th>Wins</th>
					<th>Losses</th>
				</tr>
			</thead>
			<tbody>
				<% @sorted_champ_stats.each do |champ| %>
					<tr>
						<td>
							<% champion = Champion.find_by(name: champ["champion"]) %>
							<%= link_to champ["champion"], champion %>
						</td>
						<td><%= champ["contests"] %></td>
						<td><%= champ["contest_rate"] %></td>
						<td><%= champ["picks"] %></td>
						<td><%= champ["bans"] %></td>
						<td><%= champ["winrate"] %></td>
						<td><%= champ["wins"] %></td>
						<td><%= champ["losses"] %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/champions/show.html.erb
<div class="row">
	<div class="col-md-12" align="center"><h1><%= @champion.name %></h1></div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Player</th>
					<th>Games</th>
					<th>Winrate</th>
					<th>Wins</th>
					<th>Losses</th>
					<th>Kills</th>
					<th>Deaths</th>
					<th>Assists</th>
					<th>CS</th>
					<th>Gold</th>
					<th>Wards</th>
					<th>Greens</th>
					<th>Pinks</th>
				</tr>
			</thead>
			<tbody>
				<% @sorted_player_stats.each do |player| %>
					<tr>
						<td><%= player["object"].name %></td>
						<td align="right"><%= player["stats"]["games"] %></td>
						<td align="right">
							<%= (player["stats"]["wins"].to_f / player["stats"]["games"] * 100).round(1) %>
						</td>
						<td align="right"><%= player["stats"]["wins"] %></td>
						<td align="right"><%= player["stats"]["losses"] %></td>
						<td align="right"><%= player["stats"]["kills"] %></td>
						<td align="right"><%= player["stats"]["deaths"] %></td>
						<td align="right"><%= player["stats"]["assists"] %></td>
						<td align="right"><%= player["stats"]["cs"] %></td>
						<td align="right"><%= player["stats"]["gold"] %></td>
						<td align="right"><%= player["stats"]["wards_placed"] %></td>
						<td align="right"><%= player["stats"]["greens"] %></td>
						<td align="right"><%= player["stats"]["pinks"] %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/in_house/index.html.erb
<div class="row">
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
	    <ul class="nav navbar-nav pull-left">
	        <li><%= link_to "ALL3NVAN 3LO", root_path %></li>
	    </ul>
	    
	    <ul class="nav navbar-nav pull-right">
	        <li><%= link_to "SUMMONERS", players_path %></li>
	        <li><%= link_to "CHAMPIONS", champions_path %></li>
	        <li><%= link_to "ABOUT", about_path %></li>
	    </ul>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ALL3NVAN 3LO</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <%= render 'layouts/header' %>
  <body>
    <div id="main-container" class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row">
	<div class="col-md-12">
		<center><%= image_tag("yolo.jpg", alt: "MFW") %></center>
	</div>
</div>

app/views/pages/home.html.erb
<div class ="center jumbotron" align="center">
    <h1>IN-HOUSE STATS</h1>
</div>

app/views/players/index.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4" align="center">
		<%= form_tag(players_path, method: "get") do %>
			<%= label_tag(:minimum, "Minimum games:") %>
			<% default = params[:minimum].nil? ? 5 : params[:minimum].to_i %>
			<%= number_field_tag(:minimum, default, {in: 1..100, step: 1}) %>
		<% end %>
	</div>
</div>

<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Rank</th>
					<th>Summoner</th>
					<th>Winrate</th>
					<th>Wins</th>
					<th>Losses</th>
				</tr>
			</thead>
			<tbody>
				<% @sorted_winrates.each_index do |i| %>
					<tr>
						<td><%= i + 1 %></td>
						<td><%= link_to @sorted_winrates[i]["object"].name,
										@sorted_winrates[i]["object"] %></td>
						<td align="right"><%= @sorted_winrates[i]["winrate"] %></td>
						<td align="right"><%= @sorted_winrates[i]["wins"] %></td>
						<td align="right"><%= @sorted_winrates[i]["losses"] %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/players/show.html.erb
<div class="row">
	<div class="col-md-12" align="center"><h1><%= @player.name %></h1></div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Champion</th>
					<th>Games</th>
					<th>Winrate</th>
					<th>Wins</th>
					<th>Losses</th>
					<th>Kills</th>
					<th>Deaths</th>
					<th>Assists</th>
					<th>CS</th>
					<th>Gold</th>
					<th>Wards</th>
					<th>Greens</th>
					<th>Pinks</th>
				</tr>
			</thead>
			<tbody>
				<% @sorted_stats.each do |champ| %>
					<tr>
						<td><%= champ["champion"] %></td>
						<td align="right"><%= champ["games"] %></td>
						<td align="right">
							<%= (champ["wins"].to_f / champ["games"] * 100).round(1) %>
						</td>
						<td align="right"><%= champ["wins"] %></td>
						<td align="right"><%= champ["losses"] %></td>
						<td align="right"><%= champ["kills"] %></td>
						<td align="right"><%= champ["deaths"] %></td>
						<td align="right"><%= champ["assists"] %></td>
						<td align="right"><%= champ["cs"] %></td>
						<td align="right"><%= champ["gold"] %></td>
						<td align="right"><%= champ["wards_placed"] %></td>
						<td align="right"><%= champ["greens"] %></td>
						<td align="right"><%= champ["pinks"] %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>